version: '3'
services:
  frontend:
    image: nandini965/frontend-expence:latest
    container_name: frontend-nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    image: nandini965/backend-expence:latest
    container_name: backend-nodejs
    environment:
      DB_HOST: mysql-db
      DB_USER: expense
      DB_PASSWORD: ExpenseApp@1
      DB_NAME: expence_db
    ports:
      - "5000:5000"
    depends_on:
      - expence-db
    command: ["sh", "-c", "sleep 10 && npm start"]  # Delay startup to wait for MySQL

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ExpenseApp@1
      MYSQL_DATABASE: expence_db
      MYSQL_USER: expense
      MYSQL_PASSWORD: ExpenseApp@1
    ports:
      - "3306:3306"
