replicaCount: 3

frontend:
  image: nandini965/frontend-expence:latest
  port: 80

backend:
  image: nandini965/backend-expence:latest
  port: 8080
  env:
    DB_HOST: mysql-db
    DB_PORT: "3306"
    DB_USER: expense
    DB_PASSWORD: ExpenseApp@1
    DB_NAME: transactions


#
"mysql-db":
   image: mysql:latest
   port: 3306
   rootPassword: ExpenseApp@1
   database: transactions
   user: expense
   password: ExpenseApp@1

#
ingress:
  enabled: true
  host: expence-app.local
