apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_HOST
              value: "{{ .Values.backend.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.backend.env.DB_PORT }}"
            - name: DB_USER
              value: "{{ .Values.backend.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.backend.env.DB_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.backend.env.DB_NAME }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: "{{ index .Values "mysql-db" "image" }}"
          ports:
            - containerPort: "{{ index .Values "mysql-db" "port" }}"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{ index .Values "mysql-db" "rootPassword" }}"
            - name: MYSQL_DATABASE
              value: "{{ index .Values "mysql-db" "database" }}"
            - name: MYSQL_USER
              value: "{{ index .Values "mysql-db" "user" }}"
            - name: MYSQL_PASSWORD
              value: "{{ index .Values "mysql-db" "password" }}"