# Ingress resource for the application
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-project-on-expense
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: new-project-on-expense
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: new-project-on-expense
                port:
                  number: {{ .Values.appPort }}
                  #