apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: {{ index .Values "mysql-db" "port" }}
      targetPort: {{ index .Values "mysql-db" "port" }}
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db-nodeport
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: {{ index .Values "mysql-db" "port" }}
      targetPort: {{ index .Values "mysql-db" "port" }}
  type: NodePort


